In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
### Sentence
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
## Define the vocabulary size
voc_size = 10000

In [31]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[2106, 4851, 1358, 9178],
 [2106, 4851, 1358, 5000],
 [2106, 2213, 1358, 7233],
 [7463, 8360, 4211, 6940, 654],
 [7463, 8360, 4211, 6940, 210],
 [6384, 2106, 267, 1358, 4574],
 [3659, 811, 5071, 6940]]

In [32]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [33]:
import numpy as np

In [34]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2106 4851 1358 9178]
 [   0    0    0    0 2106 4851 1358 5000]
 [   0    0    0    0 2106 2213 1358 7233]
 [   0    0    0 7463 8360 4211 6940  654]
 [   0    0    0 7463 8360 4211 6940  210]
 [   0    0    0 6384 2106  267 1358 4574]
 [   0    0    0    0 3659  811 5071 6940]]


In [47]:
## Feature representation
dim=10

In [48]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

C:\Users\waqar\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [49]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [53]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[ 0.01367141, -0.02649692,  0.03010592, -0.00381689,  0.03033819,
         0.04889419, -0.04430431,  0.02959963, -0.02966242, -0.03248713],
       [ 0.01367141, -0.02649692,  0.03010592, -0.00381689,  0.03033819,
         0.04889419, -0.04430431,  0.02959963, -0.02966242, -0.03248713],
       [ 0.01367141, -0.02649692,  0.03010592, -0.00381689,  0.03033819,
         0.04889419, -0.04430431,  0.02959963, -0.02966242, -0.03248713],
       [ 0.01367141, -0.02649692,  0.03010592, -0.00381689,  0.03033819,
         0.04889419, -0.04430431,  0.02959963, -0.02966242, -0.03248713],
       [ 0.00384591, -0.04610867,  0.0074497 ,  0.04574842,  0.03447569,
        -0.01077479,  0.02507004,  0.04826157, -0.04497281, -0.01694302],
       [ 0.03551671, -0.03383024, -0.04780736, -0.02718148,  0.02244976,
        -0.03096792, -0.03001082,  0.04165584,  0.045797  , -0.04178412],
       [-0.04657265,  0.01249902,  0.01763841, -0.00980375,  0.01969036,
        -0.00094924, -0.01888169,  0.03908357

In [54]:
embedded_docs[0]

array([   0,    0,    0,    0, 2106, 4851, 1358, 9178], dtype=int32)

In [55]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[ 0.01367141, -0.02649692,  0.03010592, -0.00381689,  0.03033819,
         0.04889419, -0.04430431,  0.02959963, -0.02966242, -0.03248713],
       [ 0.01367141, -0.02649692,  0.03010592, -0.00381689,  0.03033819,
         0.04889419, -0.04430431,  0.02959963, -0.02966242, -0.03248713],
       [ 0.01367141, -0.02649692,  0.03010592, -0.00381689,  0.03033819,
         0.04889419, -0.04430431,  0.02959963, -0.02966242, -0.03248713],
       [ 0.01367141, -0.02649692,  0.03010592, -0.00381689,  0.03033819,
         0.04889419, -0.04430431,  0.02959963, -0.02966242, -0.03248713],
       [ 0.00384591, -0.04610867,  0.0074497 ,  0.04574842,  0.03447569,
        -0.01077479,  0.02507004,  0.04826157, -0.04497281, -0.01694302],
       [ 0.03551671, -0.03383024, -0.04780736, -0.02718148,  0.02244976,
        -0.03096792, -0.03001082,  0.04165584,  0.045797  , -0.04178412],
       [-0.04657265,  0.01249902,  0.01763841, -0.00980375,  0.01969036,
        -0.00094924, -0.01888169,  0.03908357